# Generated by Django 5.0.2 on 2024-02-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
