# Generated by Django 5.0.2 on 2024-02-19 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_comment_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='main_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='home.comment'),
        ),
    ]
