# Generated by Django 5.0.2 on 2024-03-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_likemodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
