# Generated by Django 5.0.2 on 2024-03-03 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_post_saved_savedpostsmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpostsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='savedpostsmodel',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
