# Generated by Django 5.0.2 on 2024-03-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_savedpostsmodel_user_savedpostsmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpostsmodel',
            old_name='user',
            new_name='users',
        ),
    ]
