# Generated by Django 4.1 on 2024-03-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_user_savedpostsmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='main_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='home.comment'),
        ),
        migrations.AlterField(
            model_name='dislikemodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_dislikes', to='home.comment'),
        ),
        migrations.AlterField(
            model_name='dislikemodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_dislikes', to='home.post'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_likes', to='home.comment'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_likes', to='home.post'),
        ),
    ]
