# Generated by Django 4.1 on 2024-03-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_comment_main_post_alter_comment_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(default='[deleted]', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replies', to='home.comment'),
        ),
    ]
