# Generated by Django 4.1 on 2024-03-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_comment_is_deleted_dislikemodel_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='main_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post'),
        ),
    ]
