# Generated by Django 4.1 on 2024-03-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_comment_main_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
