# Generated by Django 4.1 on 2024-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_notification_receiver_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
