# Generated by Django 4.1 on 2024-03-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_notification_notif_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
