# Generated by Django 4.1 on 2024-03-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_notification_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
