# Generated by Django 5.0.2 on 2024-03-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='banner_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images'),
        ),
    ]
